# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cd09b567fc00d5014835071f239bae0e12d1926cfcd24e28799b5a766443e31942c3e88c3c44338a6c0ec1cce0712a0dc15d8da124f50aead38e2c944411dd1

test:
  secret_key_base: 3ac6b665c8b577f045c7e85427baa86a0aa50c2b03b7d5f97f2b622ff503d60b6a2f91c9915e47f64b64764e92174e4fc72c25c7884b4fb50386945ed1beea1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
